### ISSUE TITLE
[metal-uri] [question] Why replacing + character with a blank space?

### ISSUE THREAD

**Issue by albertmourato** [metal/metal-plugins#119]
We are facing a problem when using the `metal-uri` component because of this:
https://github.com/metal/metal-plugins/blob/master/packages/metal-uri/src/Uri.js#L467
We saw that you are replacing it because of a library, but is it really necessary?
In short, if a user email contains a `+`, it breaks all our API requests related to user updating since the `uriDecode` is replacing the `+` sign with a blank space.
Here goes a reproducible code of the issue we're facing:
[test-uri-issue.zip](https://github.com/metal/metal-plugins/files/2828548/test-uri-issue.zip)

**Comment by jbalsas** [comment]
Hey @albertmourato, the comment you point out doesn't say we're doing it because of **a** library but because of **the javascript library**, which simply means the default browser behaviour.

In the test sample you attach, the url you're passing doesn't even seem to be encoded at all... so why trying to decode it?

When URL-encoding, reserved characters are replaced by their percent-based equivalent. In particular, `+` characters should be turned into `%2B` and spaces should be replaced by `+` symbols in the encoded string.

The wikipedia [Percent encoding](https://en.wikipedia.org/wiki/Percent-encoding) article has a comprehensive description of the algorithm. In [Javascript Madness: Query String Parsing](https://unixpapa.com/js/querystring.html) you can read about the rationale of the code you're seeing in `metal-uri`.

Based on this, I presume the code is correct and that it's likely the usage you're doing might not be. Could you take a closer look at this to see if we can sort it out?

Thanks!

**Comment by albertmourato** [comment]
Hi @jbalsas .

Thank you so much for your detailed explanation.
That must be a problem on our side.
I tried locally adding a `encodeURIComponent` before calling the decode function.
As expected, it worked fine.

Thank you again.
